### ISSUE TITLE
Could not delete files/folders via rabbitvcs

### ISSUE THREAD

**Issue by jaheme127** [rabbitvcs/rabbitvcs#258]
I'm using the gtk3-Branch, Linux Mint 19.1 with system packages for python/git
I updated to dulwich 0.19.11, since I have trouble to get rabbitvcs working with the older version?

When I use the delete option in rabbit vcs nothing happens. -  Using git rm on the console works perfectly.

**Comment by jaheme127** [comment]
Some additional information for you:

('GOT REPO PATH', '/home/jan/Daten/Repo/Meine/egswebsite3/master')
('GITREPOCHECK', '/home/jan/Daten/Repo/Meine/egswebsite3/master', False)
('GOT REPO PATH', '/home/jan/Daten/Repo/Meine/egswebsite3/master')
ERROR	rabbitvcs.ui.delete	
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/ui/delete.py", line 77, in start
    self.vcs_remove(versioned, force=True)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/ui/delete.py", line 100, in vcs_remove
    self.vcs.git(paths[0]).remove(paths)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/git/__init__.py", line 555, in remove
    return self.client.remove(paths)
  File "/usr/lib/python2.7/dist-packages/rabbitvcs/vcs/git/gittyup/client.py", line 870, in remove
    os.remove(path)
OSError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/home/jan/Daten/Repo/Meine/egswebsite3/master/www/counter/www/counter.inc'

The stated path is wrong: correct one would be:
'/home/jan/Daten/Repo/Meine/egswebsite3/master/www/counter/counter.inc'
instead of
'/home/jan/Daten/Repo/Meine/egswebsite3/master/www/counter/www/counter.inc'

This problem happens only in the gtk3-branch

**Comment by monnerat** [comment]
The master branch is now Python 2/3 compatible and Gtk 3 only. Can you reproduce with it?

**Comment by jaheme127** [comment]
Hey the issue is resolved with the current version (python3/gtk3)

**Comment by monnerat** [comment]
@jaheme127 : thanks for feedback :-)

**Comment by jaheme127** [comment]
hey I retried and there are still cases where it doesn't work. I can delete files not assoziated to the repositary with the delete command, but if I want to delete a file which already has been commited "Delete" simply does nothing. Furthermore, there is no commandline output - so I don't know why nothing happen in this case.

"git rm" still works!

**Comment by metal450** [comment]
This issue still remains, in 2021.

If I delete a file then 'commit,' the 'changed files' portion of the commit window shows the file as missing (this is correct). However, if I proceed with the commit, the source file is restored, and the commit operation has no changes. This is obviously an error - the commit should commit the deletion, not revert the change & commit nothing.
